### ISSUE TITLE
Integrate Bentel alarm system

### ISSUE THREAD

**Issue by SamuelsonLB** [And3rsL/VisonicAlarm-for-Hassio#12]
Hello,

How I can integrate a Bentel alarm system? Because I don't have host, email or password.

I'm logging on the android app only with serial number and 4 digit password.

Thank you for your job!

**Comment by And3rsL** [comment]
I also use bentel systems, but i see username and password..

anyway you can use the old release https://github.com/And3rsL/VisonicAlarm-for-Hassio/tree/1.1.5
it support just serial and digits

**Comment by SamuelsonLB** [comment]
I only have the username and password to login on the web and download the manuals. I don't have any payment service.

What host do you use? And the panel id can be numbers and letters?

**Comment by satomma** [comment]
Any help about Bentel?

**Comment by stefanodalpos** [comment]
> I also use bentel systems, but i see username and password..
> 
> anyway you can use the old release https://github.com/And3rsL/VisonicAlarm-for-Hassio/tree/1.1.5
> it support just serial and digits

which is the correct host for bentel absoluta? i tried but don't work
