### ISSUE TITLE
Change Icons

### ISSUE THREAD

**Issue by curry756** [And3rsL/VisonicAlarm-for-Hassio#13]
Hello - great job on this integration.

Quick question, more than an "issue", but all my contacts are showing up as mdi:door-open/closed, which is ok, but most of my sensors are windows, and the icon is anoying me - is there a way to allow me to specify icon's per entity?  I can override them (per entity) in LoveLace, but it is a complete override doesnt honour the open closed state.  for example - i can override the icon to use mdi:window-open, but it always shows this icon, even when closed.

Happy new year!
Cheers
PC -

**Comment by And3rsL** [comment]
at this time there is no support for change icons
I will think about an Window/Door switch
