### ISSUE TITLE
Visonic Integration error

### ISSUE THREAD

**Issue by Endimion34** [And3rsL/VisonicAlarm-for-Hassio#16]
Hi everyone,
I begin with home assistant and i try an integration of my visonic alarm (powermaster 10 +ip modul)
I filled the file as described and Home assistant return the following message:
Thanks to help me.

Setup failed for visonicalarm: Integration failed to initialize.
7:59:53 – setup.py (ERROR)
Connection failed: 'NoneType' object is not subscriptable
7:59:49 – visonicalarm (ERROR)
{"error":10001,"error_message":"Bad Request Params","error_reason_code":"BadRequestParams","extras":[{"key":"user_code","value":"minLength:4"}]}
7:59:49 – /usr/local/lib/python3.8/site-packages/visonic/alarm.py (ERROR)
{"error":10001,"error_message":"Bad Request Params","error_reason_code":"BadRequestParams","extras":[{"key":"user_code","value":"minLength:4"}]}
7:59:49 – /usr/local/lib/python3.8/site-packages/visonic/alarm.py (ERROR)
400 Client Error: Bad Request for url: https://visonic.tycomonitor.com/rest_api/8.0/panel/login
7:59:49 – /usr/local/lib/python3.8/site-packages/visonic/alarm.py (ERROR)

**Comment by BrightClick** [comment]
im getting the same issue with :
Connection failed: 'NoneType' object is not subscriptable

**Comment by And3rsL** [comment]
Can you please share your configuration under configuration.yaml?

**Comment by BrightClick** [comment]
> Can you please share your configuration under configuration.yaml?

Sure, I'm using this config, its working great for few days, then its giving that error, and at that point every service call will give that error unless I reboot the hassio, then all will get back to normal. its happens all the time I was thinking to do automatic resets already to fix it. 

visonicalarm:
  host: !secret visonic_host
  panel_id: !secret visonic_panel_id
  user_code: !secret visonic_code
  app_id: !secret visonic_app_id
  user_email: !secret visonic_email
  user_password: !secret visonic_password
  partition: -1
  no_pin_required: true

**Comment by BrightClick** [comment]
i now see those warnings in the log, not sure its related to the issue 
2021-03-18 22:15:28 WARNING (MainThread) [homeassistant.components.alarm_control_panel] Updating visonicalarm alarm_control_panel took longer than the scheduled update interval 0:00:10
2021-03-18 22:15:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.visonic_alarm is taking over 10 seconds

**Comment by BrightClick** [comment]
Good morning, i made a video of the situation that just happened today again:
https://www.loom.com/share/9824e8fd2891431c8c82c7c55e80803d

any idea what I need to change? its seems like something with partition array

thanks

this is the full log I got from the error:

Logger: homeassistant.helpers.entity
Source: custom_components/visonicalarm/__init__.py:119
First occurred: 2:23:39 AM (2473 occurrences)
Last logged: 9:15:50 AM

Update for alarm_control_panel.visonic_alarm fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/visonicalarm/alarm_control_panel.py", line 153, in update
    hub.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 285, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/visonicalarm/__init__.py", line 119, in update
    self.alarm.update_status()
  File "/usr/local/lib/python3.8/site-packages/visonic/alarm.py", line 350, in update_status
    partition = status['partitions'][0]
TypeError: 'NoneType' object is not subscriptable

**Comment by Endimion34** [comment]
my config is the same:

visonicalarm:
  host: visonic.tycomonitor.com
  panel_id: 1XX001
  user_code: 1234
  app_id: 000000000000000uniqueid genereted00000
  user_email: ***@***.***'
  user_password: 'ABCD1234'
  partition: -1
  no_pin_required: False


my last error:
Setup failed for visonicalarm: Integration failed to initialize.
8:50:17 – (ERREUR) setup.py
Setup of zone is taking over 10 seconds.
8:50:17 – (ATTENTION) /usr/local/lib/python3.8/asyncio/events.py
Setup of binary_sensor platform hassio is taking over 10 seconds.
8:50:17 – (ATTENTION) Capteur binaire
Setup of sensor platform hassio is taking over 10 seconds.
8:50:17 – (ATTENTION) Capteur
Connection failed: 'NoneType' object is not subscriptable
8:50:16 – (ERREUR) visonicalarm
{"error":10001,"error_message":"Bad Request
Params","error_reason_code":"BadRequestParams","extras":[{"key":"user_code","value":"minLength:4"}]}
8:50:16 – (ERREUR) /usr/local/lib/python3.8/site-packages/visonic/alarm.py
{"error":10001,"error_message":"Bad Request
Params","error_reason_code":"BadRequestParams","extras":[{"key":"user_code","value":"minLength:4"}]}
8:50:16 – (ERREUR) /usr/local/lib/python3.8/site-packages/visonic/alarm.py
400 Client Error: Bad Request for url:
https://visonic.tycomonitor.com/rest_api/8.0/panel/login
8:50:16 – (ERREUR) /usr/local/lib/python3.8/site-packages/visonic/alarm.py


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le jeu. 25 mars 2021 à 08:16, Eliran Shachar ***@***.***> a
écrit :
