### ISSUE TITLE
Upgrade to 0.103.0 breakes the component

### ISSUE THREAD

**Issue by a94marbo** [And3rsL/VisonicAlarm-for-Hassio#2]
Copy paste from log:

Log Details (ERROR)
Thu Dec 12 2019 15:02:11 GMT+0100 (Central European Standard Time)
Error while setting up platform visonicalarm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/visonicalarm/alarm_control_panel.py", line 39, in setup_platform
    visonic_alarm = VisonicAlarm(hass)
TypeError: Can't instantiate abstract class VisonicAlarm with abstract methods supported_features

Log Details (ERROR)
Thu Dec 12 2019 15:02:25 GMT+0100 (Central European Standard Time)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 376, in _async_add_entity
    suggested_object_id or entity.name or DEVICE_DEFAULT_NAME
  File "/config/custom_components/visonicalarm/sensor.py", line 60, in name
    return 'Visonic Alarm Contact ' + self._id
TypeError: can only concatenate str (not "NoneType") to str

**Comment by And3rsL** [comment]
Hi! Im working about it, i will try fix it in the next days :)

**Comment by And3rsL** [comment]
easier than I expected! Just download again custom componente :D

**Comment by a94marbo** [comment]
Thanks will try it later today.
I am running hassio and I have been searching for the "visonicalarm2" module and it seems not to be automaticly downloaded as it says on in installation notes. SInce I have hassio, I hvae only copied the custom component to the folder "customer component", I am not able to run the "sudo pip3 install visonicalarm2" commad. Can I download or install this manually somehow?

**Comment by And3rsL** [comment]
if you are running hassio there is no need to download anything, it will get its dependencies automatically. you wont see

If it works it means the plugin has everything he needs

**Comment by a94marbo** [comment]
Hmm, ok. The panel works but the sensors dont show up even after the update you made in visonicalarm2 6 months ago. Now sure if the updated visonicalarm2 have been installed.

**Comment by And3rsL** [comment]
motion sensor currently doesnt work

for now you just should see in "states" tab something like this:

![Immagine](https://user-images.githubusercontent.com/31848430/70789318-10f34d80-1d93-11ea-8b96-697645064fe1.jpg)

**Comment by a94marbo** [comment]
Ok, well I dont see any visonic sensors at all apart from "alarm_control_panel.visonic_alarm".
So I guess something is wrong with my installation of visonic component. I thought maybe it was related to wrong version of "visonicalarm2".

**Comment by And3rsL** [comment]
Mhm, thats strange

Are there any error in the event log?

**Comment by a94marbo** [comment]
Got the panel working now under 0.103.0 with your update, Still no sensors.
Get this error in the log:
Fri Dec 13 2019 15:26:36 GMT+0100 (centraleuropeisk normaltid)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 376, in _async_add_entity
    suggested_object_id or entity.name or DEVICE_DEFAULT_NAME
  File "/config/custom_components/visonicalarm/sensor.py", line 60, in name
    return 'Visonic Alarm Contact ' + self._id
TypeError: can only concatenate str (not "NoneType") to str

**Comment by And3rsL** [comment]
i updated sensor.py, itt should fix the error
can you test it?

Note that only CONTACT and CONTACT_AUX will display open/closed status

For motion you will able to see just them in the sensor list but no motion is detected for now

**Comment by a94marbo** [comment]
Yep, now something happened. I got a bunch of: sensor.visonic_alarm_none_xx sensors. No errors in the log anymore.
where XX is 00 to 16. Just need to figure out what is what now : )

Thanks.

**Comment by And3rsL** [comment]
You should get  "sensor.visonic_alarm_{ID}"
where {ID} is the id of the sensor displayed in the alarm system

you can check other devices info (such as device_type and location) in the "states" tab under "developer tools" in hassio

**Comment by a94marbo** [comment]
Ok, doublechecked again, no such sensors.
just sensor.visonic_alarm_none_xx, no errors in log.

**Comment by a94marbo** [comment]
Done some more thinking (since my programmisg skills sucks). Since the front door have the first position in the alarm list of devices and the 11 is the correct number of sensors (contact and motion detectors).

It seems to me that component is reading the correct number is positions in the alarm, but do not change position for each read. It read the first position 11 times, instead of reading 11 different positions. Forgets to increment the position for each read? Like a FOR-loop where the number is not increased?
