### ISSUE TITLE
Integration failed to initialize

### ISSUE THREAD

**Issue by slack1987** [And3rsL/VisonicAlarm-for-Hassio#22]
Hi, I receive this 2 messages in the log:

2022-01-13 13:35:26 ERROR (SyncWorker_2) [custom_components.visonicalarm] Connection failed: Rest API version 8.0 is not supported by server.
2022-01-13 13:35:26 ERROR (MainThread) [homeassistant.setup] Setup failed for visonicalarm: Integration failed to initialize.

Any idea? Thank you!

**Comment by a94marbo** [comment]
Your power manage server is not running API version 8 as this integration requires. Copy this and replace it with your power manage server address.
"https://(power_manage_adress)/rest_api/version"
And paste in any browser. If you get this message:

```
{
    "rest_versions":["3.0", "4.0"],
    "installer_versions":["1.1"],
    "push_format_versions":["3", "4"],
    "user_message": ""
}
```
then you need to use an older version of the integration.
I have one working on my github:
https://github.com/a94marbo/VisonicAlarm-for-Hassio-Rest-API3_4

**Comment by slack1987** [comment]
@a94marbo This is the message I got:

```
{
    "rest_versions":["9.0"],
    "installer_versions":["7.0"],
    "push_format_versions":["7"],
    "dls_versions":["1.0"]
}

```

It looks like the power manage server is running API version 9, isn't it?

**Comment by a94marbo** [comment]
Oh, then neither I or the owner of this repo have a solution. Was not aware of yet another API version.

**Comment by slack1987** [comment]
@And3rsL any chance to have the repo back to work?
