### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by slack1987** [And3rsL/VisonicAlarm-for-Hassio#23]
Hi, after updating the package to API 9, I started having the following errors in the log:

400 Client Error: Bad Request for url: https://visonic.tycomonitor.com/rest_api/9.0/set_state

{"error":400,"error_message":"Panel is not connected","error_reason_code":"PanelNotConnected","extras":[]}

**Comment by And3rsL** [comment]
You should connect your panel to internet by sending sms via APP
