### ISSUE TITLE
Version without username and password

### ISSUE THREAD

**Issue by Murada99** [And3rsL/VisonicAlarm-for-Hassio#24]
Hi,

I use server alarmas.trablisa.es and I don't need to specify username and password.
It only requires panel id and master user code.

If I leave blank the values, I get the following error:
Invalid config for [visonicalarm]: string value is None for dictionary value @ data['visonicalarm']['user_email']. Got None
string value is None for dictionary value @ data['visonicalarm']['user_password']. Got None. (See /config/configuration.yaml, line 544).

I'm doing something wrong ?

**Comment by Murada99** [comment]
That's an old version
{
    "rest_versions":["3.0", "4.0"],
    "installer_versions":["1.1"],
    "push_format_versions":["3", "4"],
    "user_message": ""
}
I'm going to try the version 1.1.5

**Comment by Murada99** [comment]
After installation of version 1.1.5 and adding the version in the manifest.json file, it works.

**Comment by a94marbo** [comment]
> That's an old version { "rest_versions":["3.0", "4.0"], "installer_versions":["1.1"], "push_format_versions":["3", "4"], "user_message": "" } I'm going to try the version 1.1.5

Have you got integration to work with the old Rest API 3 and 4?

**Comment by Murada99** [comment]
Yes, but with version 1.1.5 and not the latest and by adding the version in the manifest.json file.
