### ISSUE TITLE
Can't integrate visonic powermaster 10

### ISSUE THREAD

**Issue by sharonoren1** [And3rsL/VisonicAlarm-for-Hassio#25]
Hi all,

I added this to configuration.yaml:
visonicalarm:
  host: visonic.tycomonitor.com
  panel_id: xxxxxx
  user_code: xxxx
  app_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
  user_email: myemail@gmail.com
  user_password: password as used by visonic-go app
  partition: -1
  no_pin_required: False

and I got the error: 
Logger: root
Source: /usr/local/lib/python3.9/site-packages/visonic/alarm.py:607
First occurred: 20:26:01 (1 occurrences)
Last logged: 20:26:01

{"error":10004,"error_message":"Wrong combination","error_reason_code":"WrongCombination","extras":[{"key":"email","value":"wrong_combination"},{"key":"password","value":"wrong_combination"}]}

What I'm doing wrong? 
Please help..

**Comment by chrisns** [comment]
Suspect your creds aren't right, or they're not for user id 1?
If you've got any special characters in your password maybe make sure they're escaped?

**Comment by sharonoren1** [comment]
> Suspect your creds aren't right, or they're not for user id 1? If you've got any special characters in your password maybe make sure they're escaped?

Hi Chris,

Thanks for your answer.
I'm using the same values panel_id, user_code and user_email by Visonic-Go app without any problem.
There is a different between Version 1 / 4 UUID Generator? 
Maybe I need to use quotes after the two points or something else?

Regards,
Oren

**Comment by chrisns** [comment]
¯\_(ツ)_/¯

Try changing your creds?

**Comment by sharonoren1** [comment]
> ¯_(ツ)_/¯
> 
> Try changing your creds?

Thanks friend! 
It's work after I changed my password
