### ISSUE TITLE
Can't create script by alarm trigger

### ISSUE THREAD

**Issue by sharonoren1** [And3rsL/VisonicAlarm-for-Hassio#26]
Hi,

I can't create a script that send me notification when the alarm is triggered.
I field the script like the photo.
![image](https://user-images.githubusercontent.com/77583793/154815304-bec8846c-d4ab-43d2-ada9-966b30f7c039.png)

Please help me.
Regards,
Oren

**Comment by Murada99** [comment]
Try this:

![image](https://user-images.githubusercontent.com/48693406/222681933-3da6cd8a-f80c-428a-87af-fdb132e3d65c.png)

**Comment by haldi4803** [comment]
There is no more "alarm" attribute.

<img width="381" height="503" alt="Image" src="https://github.com/user-attachments/assets/133e7fee-e8fb-4765-8329-d15a53e0df34" />

And as said before, the "trigger" doesn't work. 

<img width="623" height="703" alt="Image" src="https://github.com/user-attachments/assets/16947bb9-afee-4bab-b1a3-21745264755f" />
