### ISSUE TITLE
Integration fails to start

### ISSUE THREAD

**Issue by muxa** [And3rsL/VisonicAlarm-for-Hassio#29]
The integration worked fine, until at some point it stopped loading. Here are the logs:

```
Logger: custom_components.visonicalarm
Source: custom_components/visonicalarm/__init__.py:66 
Integration: visonicalarm (documentation) 
First occurred: 10:20:35 (1 occurrences) 
Last logged: 10:20:35

Connection failed: Rest API version 8.0 or 9.0 is not supported by server.
```

**Comment by muxa** [comment]
I found that API for my alarm is now using version `10.0`. I've created an issue to add support for this version: https://github.com/And3rsL/VisonicAlarm2/issues/3

**Comment by labbs1** [comment]
Same here...

**Comment by progamer562** [comment]
same here too this integration is useless without an update

**Comment by progamer562** [comment]
i have made antoher project https://github.com/progamer562/Visonic-Bentel-Tyco-Alarm-System-2
@muxa apply your pull request

**Comment by progamer562** [comment]
this is closed so that means you fixed it?

**Comment by And3rsL** [comment]
> this is closed so that means you fixed it?

Yes
