### ISSUE TITLE
Code arm required

### ISSUE THREAD

**Issue by PetitBiscuit77** [And3rsL/VisonicAlarm-for-Hassio#34]
Since HA core 2024.6 I encountered an issue when I want arm with alarm panel.
There is a change with this version and when I armed I got this message "Arming requires a code but none was given for alarm_control_panel.visonic" this sentense appears because by default now we have this option set True so code_arm_required: false needs to be set for the alarm_control_panel of the visonic integration otherwise I can't arm manually or with my automation without code
Please let me know if it's possible to integrade this setting on integration
During this time I have rollback on previous version
Thanks you

**Comment by PetitBiscuit77** [comment]
You can check this fix

https://github.com/home-assistant/core/pull/118961

**Comment by pawellygan** [comment]
> Since HA core 2024.6 I encountered an issue when I want arm with alarm panel. There is a change with this version and when I armed I got this message "Arming requires a code but none was given for alarm_control_panel.visonic" this sentense appears because by default now we have this option set True so code_arm_required: false needs to be set for the alarm_control_panel of the visonic integration otherwise I can't arm manually or with my automation without code Please let me know if it's possible to integrade this setting on integration During this time I have rollback on previous version Thanks you

did you solve it? I'm facing same issues with code

**Comment by PetitBiscuit77** [comment]
> > Since HA core 2024.6 I encountered an issue when I want arm with alarm panel. There is a change with this version and when I armed I got this message "Arming requires a code but none was given for alarm_control_panel.visonic" this sentense appears because by default now we have this option set True so code_arm_required: false needs to be set for the alarm_control_panel of the visonic integration otherwise I can't arm manually or with my automation without code Please let me know if it's possible to integrade this setting on integration During this time I have rollback on previous version Thanks you
> 
> 
> 
> did you solve it? I'm facing same issues with code

Yes but with a workaround because I wait the next development from the owner.
You can fix it if you add the line _attr_arm_......: 
![image](https://github.com/And3rsL/VisonicAlarm-for-Hassio/assets/129862176/8133da98-92fd-4823-ba4d-746b550a3a1b)
