### ISSUE TITLE
Bentel Support

### ISSUE THREAD

**Issue by madmicio** [And3rsL/VisonicAlarm-for-Hassio#5]
congratulations for the work, I saw on hacs that bentel is also reported in the title.
which control panels are supported?
my control panel has a UUID in this format

abc12345
id:
1 2 3 4

**Comment by lelepando** [comment]
I succesfully connected my Bentel BW 30 + IPCOM card using this integration

**Comment by madmicio** [comment]
I have an absoluta 42, but I don't have the correct uuid format.
Has anyone integrated the absoluta series?  How can I get the data needed for this integration?

**Comment by And3rsL** [comment]
This custom component only support Bentel BW30/64

Or more generally all bentel system uses this app: https://play.google.com/store/apps/details?id=com.visonic.BWApp&hl=it
