### ISSUE TITLE
Motion Sensors Only, Missing Contact and Shock Sensors

### ISSUE THREAD

**Issue by maurolencioni** [And3rsL/VisonicAlarm-for-Hassio#6]
Hi
Thank you for developing this integration.  I am using a PowerMaster-33 and the alarm panel component is arming/disarming well.  All the motion sensors have been integrated as entities.  The contact and vibration/shock/contact sensors have not been integrated and are missing from HA.  I am new at this so perhaps missing something.
Thank you for your help.

**Comment by lelepando** [comment]
I have a similar situation.
Only simple contact sensor s and motion sensors has been integrated, but all other contact+ shock detector didn't come into HA...

Daniele

**Comment by And3rsL** [comment]
Sorry but for now only contact sensors are supported!
even motion are visible in HA but does nothing

**Comment by maurolencioni** [comment]
> Sorry but for now only contact sensors are supported!
> even motion are visible in HA but does nothing

No problem.  Good work so far.  I will keep checking in.
