### ISSUE TITLE
not all contacts work

### ISSUE THREAD

**Issue by curry756** [And3rsL/VisonicAlarm-for-Hassio#9]
Hello,

Great plugin!  Can see massive potential in me using this. However I am stuck... 

I am setting this up and I have a fair few of shock contacts.  they are identified as:```SHOCK_CONTACT_AUX_ANTIMASK```

I have added this into the sensor.py on my local machine which identifies and adds the sensors

```
    for device in hub.alarm.devices:
        if device.subtype == 'SHOCK_CONTACT_AUX_ANTIMASK' or device.subtype == 'CONTACT_AUX' or device.subtype == 'CONTACT' or device.subtype == 'MOTION_CAMERA' or device.subtype == 'MOTION' or device.subtype == 'CURTAIN':
          _LOGGER.debug("New device found [Type:" + str(device.subtype) + "] [ID:" + str(device.id) + "]")
          add_devices([VisonicAlarmContact(hub.alarm, device.id)], True)
```

however, they don't seem to return "open" or "closed", so they are showing as unknown and are currently useless.  Anyone know what they return for open and closed state? I can code it myself if i know

Thanks in advance.

**Comment by And3rsL** [comment]
Does it report open/closed state on the official app?

**Comment by curry756** [comment]
Hello - Thanks for getting back to me - yes it does.  As you can see, the "Front Door" is a contact sensor and the "Master Bedroom" is the shock contact senser:

![IMG_2846](https://user-images.githubusercontent.com/15815910/95559175-43032980-0a0f-11eb-919c-a96c561ca30d.PNG)
![IMG_2845](https://user-images.githubusercontent.com/15815910/95559179-44345680-0a0f-11eb-97df-9056c74ac30d.PNG)
![IMG_2844](https://user-images.githubusercontent.com/15815910/95559181-44cced00-0a0f-11eb-86b6-5704feb921d3.PNG)
![IMG_2842](https://user-images.githubusercontent.com/15815910/95559182-45658380-0a0f-11eb-931a-f04ebd8d8cad.PNG)

**Comment by And3rsL** [comment]
Will fix it in the next release

**Comment by curry756** [comment]
Thanks - any idea when that will be?

**Comment by And3rsL** [comment]
please update and try it 👍

**Comment by curry756** [comment]
PERFECT THANKS its working now!  

Any plans to get mostion sensors and smoke detectors working in here too as they clould be useful too?  Separate issues I know :)

Cheers
